### ISSUE TITLE
[Bug] : Can't see the rest of the tags on the card.

### ISSUE THREAD

**Issue by apikmeister** [dev-AshishRanjan/Idea-Arca#29]
**Describe the bug**
Tags on idea card are not fully show. The overflow is not been handle properly.

**To Reproduce**

1. Go to any 'section' (such as React)
2. You can see the card tags is not showing properly

**Expected behavior**
If the tags is more than what the card can display properly, there must be hovered button that shows the rest of the tags. (Such as +5)

**Screenshots**

![Screenshot 2023-10-12 at 1 45 10 AM](https://github.com/dev-AshishRanjan/Idea-Arca/assets/92358212/374c4bf7-7112-48a6-958b-84b09f2eea17)

**Desktop:**

- OS: MacOS Ventura
- Browser: Arc (Chromium based)
- Version 1.11.0

**Additional context**
I believe I can fix this issue, you are open to assign this issue to me.

**Comment by dev-AshishRanjan** [comment]
It has been done intentionally to make cards have same height

**Comment by dev-AshishRanjan** [comment]
@apikmeister ,
you can add new themes or new ideas to this repo
